apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hf-api
  name: hf-api
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hf-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hf-api
    spec:
      containers:
      - env:
        - name: HF_MONGO
          value: mongodb://mongodb/hfProd
        - name: DEBUG
          value: "hardfork:*"
        image: gcr.io/main-219410/hf-api:latest
        imagePullPolicy: Always
        name: hf-api
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP

