apiVersion: v1
kind: Service
metadata:
  labels:
    app: hf-api
  name: hf-api
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3001
  selector:
    app: hf-api
  type: ClusterIP
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: hf-api
spec:
  host: api.hardforks.info
  service: hf-api:8080
  prefix: /
