apiVersion: v1
kind: Service
metadata:
  labels:
    app: hf-api
  name: hf-api
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3001
  selector:
    app: hf-api
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  name: hf-api
  namespace: default
spec:
  rules:
  - host: api.hardforks.info
    http:
      paths:
      - backend:
          serviceName: hf-api
          servicePort: 8080
